version: 0.2

phases:
  install:
    runtime-versions: 
      dotnet: 3.0
  build:
    commands:
      - cd src
      - dotnet restore
      - dotnet build
artifacts:
  files:
    - .\bin\Debug\netcoreapp3.0\*
